myapp/urls.py
from django.urls import path
from . import views

app_name='myapp'

urlpatterns = [
    path('',views.index, name='index'),
    path('<int:id>/',views.detail, name='detail'),
    path('add/',views.create_item, name='create_item'),
    path('update/<int:id>/',views.update_item, name='update_item'),
    path('delete/<int:id>/',views.delete_item, name='delete_item'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
]

myapp/forms.py
from django import forms
from .models import Item

class Itemform(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from .forms import Itemform
# Create your views here.
def index(request):
    #getting items from database
    item_list = Item.objects.all()
    #creating context
    context={
        'item_list':item_list
    }
    # passing the context object to the render method along the template
    return render(request,"myapp/index.html",context)


def detail(request,id):
    #created a detailed veiw for each item
    item=Item.objects.get(id=id)
    context={
        'item':item
    }
    return render(request,"myapp/detail.html",context)

def create_item(request):
    form= Itemform(request.POST or None)
    
    if request.method=="POST":
        if form.is_valid():
            form.save()
            return redirect('myapp:index')
    
    #using the form here to render veiw
    context = {
        'form':form
    }
    return render(request, "myapp/item-form.html", context)

def update_item(request,id):
    item = Item.objects.get(id=id)
    form = Itemform(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('myapp:index')
        
    context ={
        'form':form
    }
    return render(request, "myapp/item-form.html", context)

def delete_item(request, id):
    item = Item.objects.get(id=id)
    if request.method=="POST":
        item.delete()
        return redirect('myapp:index')
    
    return render(request, "myapp/item-delete.html")

myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <title>Document</title>
</head>
<body>
    <nav class="bg-blue-400 text-white">
        <div class="flex justify-between px-2 py-4">
            <a  class="font-bold text-2xl" href="">Food App</a>
            <div class="space-x-5">
                <a href="">Contact</a>
                <a href="">Address</a>
                <a href="">About Us</a>
            </div>
        </div>
    </nav>
    {% block body%}
    {% endblock %}
</body>
</html>

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block body %}
<div>
    <div class="flex m-10 w-1/3 mx-auto">
        <div>
            <h1 ><img class="w-84 rounded-lg" src="{{item.item_image}}" alt="placeholder"></h1>
        </div>
        <div class="p-4 my-auto mx-5 space-y-4">
            <div class="font-bold text-4xl">{{item.item_name}}</div>
            <div class="text-green-500 text-2xl font-bold">₹{{item.item_price}}</div>
            <div>{{item.item_desc}}</div>
            
            <div class="my-4">
                <a class="px-3 py-1 bg-yellow-500 rounded-md" href="{% url 'myapp:update_item' item.id %}">Edit</a>
                <a class="m-2 px-3 py-1 bg-red-400 text-white rounded-md" href="{% url 'myapp:delete_item' item.id %}">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block body %}

<div class="">
    {% for item in item_list %}
    <div class="flex w-1/2 mx-auto py-5">
        <div>
            <img class="w-64 rounded-lg" src="{{item.item_image}}" alt="placeholder">
        </div>
        <div class="mx-30 space-y-4 py-4 text-left">
            <div class="font-bold text-4xl text-left">{{ item.item_name }}</div>
            <div>{{ item.item_desc }}</div>
            <div class="font-bold text-green-500 text-2xl">₹{{ item.item_price }}</div>
        </div>
        <div class="mx-auto py-4">
            <a class="bg-red-500 text-white px-5 py-2 rounded-xl" href="{%url 'myapp:detail' item.id %}">Veiw details</a>
        </div>
    </div>
    
    {% endfor %}
</div>

{% endblock %}

myapp/templates/myapp/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure?</h2>
    <button type="submit">Confirm</button>
</form>

myapp/templates/myapp/item-form.html
{% extends 'myapp/base.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Save</button>

</form>

{% endblock %}